server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true  
    gateway:
      discovery:
        enabled: true
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: employeeservice
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/rest/emp/**
        - id: departmentservice
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/rest/dept/**             
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     serviceUrl:
       defaultZone: http://localhost:8761/eureka
     instance: localhost
     preferIpAddress: true
     lease-renewal-interval-in-seconds: 10
     lease-expiration-duration-in-seconds: 20     
    
   

